# Generated by Django 6.0.7 on 2026-08-09 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlhandler', '0004_alter_shorturl_short_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shorturl',
            name='visits',
        ),
    ]
